[env:matek_f405]
platform = ststm32
board = genericSTM32F405RG
framework = arduino
board_build.f_cpu = 168000000L

lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio

board_microros_transport = serial
board_microros_distro = humble